### ISSUE TITLE
インストール中にエラー

### ISSUE THREAD

**Issue by hidemaru76** [suer/redmine_milkode#1]
はじめまして。hidemaru76と申します。
redmineでのソースコード検索のため、当プラグインを使用させていただきたいと思っております。

実際にプラグインのインストールを始めたところ、以下のエラーが表示され困っております。
An error occurred while installing rroonga (4.0.0), and Bundler cannot continue.
Make sure that `gem install rroonga -v '4.0.0'` succeeds before bundling.

解決方法等、ご教授頂けないでしょうか？
環境は、CentOS 6.5、Redmine 2.3.4.stableです。

**Comment by suer** [comment]
エラーメッセージを見ないとなんとも言えませんが、rrooga のビルドログにヒントはないでしょうか？

ただ、このプラグインはちょっと古く、最新の milkode および rroonga に追従してませんので
最新のものをがんばって入れてもうまく動かないかもしれません。

当方は、
- CentOS release 5.9 (Final)
- Redmine 2.4.2
- milkode 0.6.3
- rroonga 3.1.0

で動いてます。

**Comment by hidemaru76** [comment]
早急なご連絡ありがとうございます。
再度インストールを試みましたが、下記のようなメッセージが表示されております。

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
/usr/bin/ruby extconf.rb 
```

checking for GCC... yes
checking for Win32 OS... no
checking for groonga version (>= 4.0.0)... no
downloading http://packages.groonga.org/source/groonga/groonga-4.0.0.tar.gz... done
extracting... done
configuring... done
building (maybe long time)... failed
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

環境が好ましくない状態なのか、インストールに必要なものが足りていないのでしょうか？

**Comment by kenhys** [comment]
Groongaの必要なパッケージがインストールされていなくて、ソースからビルドしようとして失敗しているように見えます。
なので、まずはGroongaをパッケージでインストールした状態で試すといいのではないかと思います。
CentOS 6.5ということなので、以下のようにしてGroongaの開発パッケージをまずはインストールしてみてください。

http://groonga.org/ja/docs/install/centos.html#centos-6

```
% sudo rpm -ivh http://packages.groonga.org/centos/groonga-release-1.1.0-1.noarch.rpm
% sudo yum makecache
% sudo yum install -y groonga-devel
```

**Comment by hidemaru76** [comment]
kenhysさん

ご教授ありがとうございます。
お教えいただいた方法を試してみたいと思います。

**Comment by hidemaru76** [comment]
kenhysさん

ご教授いただいた方法でmilkodeプラグインのインストールができました。
ありがとうございました。

suerさん

一点お教えいただけないでしょうか。
現在は、Subversionで管理されているソースコードは対応となっておりますか？

**Comment by suer** [comment]
残念ながら Subversion は今も非対象です。
現在私は Subversion をまったく使わないので特に対応する予定はありませんが、pull request は随時受け付けております。

**Comment by hidemaru76** [comment]
ご回答ありがとうございます。
Subversionは非対象とのこと了解しました。
Gitで利用してみたいと思います。
